<?php
    include("head.php");
?>

<body>

<div class="wrapper">

    <?php 
        include("banner_nav.php");
    ?>

    <main class="pad-20">
    <h2>Welcome</h2>

    <p>
        You can use this website to learn about unofficial holidays.  Please use the tools on the left hand side to explore.
    </p>

    <p>
        Not sure where to start?  Take a look at a few random holidays.
    </p>

    <p>
        The content was <a href="https://chatgpt.com/">generated by Chat GPT</a> (so there may be some mistakes).  The images were sourced from...
    </p>

    <ul>
        <li><a href="https://www.svgrepo.com/">SVG Repo</a></li>
        <li><a href="https://pixabay.com/">Pixabay</a></li>
        <li><a href="https://gemini.google.com/">Gemini AI</a></li>
    </ul>

    <p>
        They were then edited using Illustrator and GIMP.    
    </p>

</main>

<?php
    include("footer.php");
?>

</div>  <!-- / wrapper -->


</body>

</html>